### ISSUE TITLE
Google keeps stopping

### ISSUE THREAD

**Issue by RikKoedoot** [KieronQuinn/DiscoverKiller#3] opened 2021-08-17 22:08 UTC
The Google apps keeps stopping since I've installed the module, I did follow the installation instructions, setting a different app to open does work, but opening snapshot does not work. Couldn't get a crash log via scoop

**Comment by KieronQuinn** [comment] 2021-08-17 22:39
You should be able to get a crash log from the crash dialog, use the send feedback option (but don't actually send it, let's not annoy Google), then send a screenshot of the Stack Trace option

**Comment by nonyonah** [comment] 2021-08-18 08:17
Yeah, I've got the same issue. I also get a reload timed out too

**Comment by nonyonah** [comment] 2021-08-18 08:24
![Screenshot_20210818-092229](https://user-images.githubusercontent.com/53056536/129864261-da344345-e501-4010-b678-eace51dc4d94.png)
![Screenshot_20210818-092238](https://user-images.githubusercontent.com/53056536/129864274-a50ecd3f-abae-4bda-a876-9010a3c1daef.png)

Here are screenshots of the stack trace

**Comment by RikKoedoot** [comment] 2021-08-18 12:26
![Screenshot_20210818-142511.jpg](https://user-images.githubusercontent.com/29402532/129897699-4e7cf57d-c166-4568-84c8-fb2a7e36ff99.jpg)
Here's mine. Idk if it matters but I'm using lsposed.

**Comment by KieronQuinn** [comment] 2021-08-18 14:13
That's a relatively simple fix for me, but shouldn't be happening. Do you have a different Snapshot UI? Can you send a screenshot of the Snapshot UI when opened from the Google app? (it shouldn't crash when launched that way)

**Comment by RikKoedoot** [comment] 2021-08-18 14:42
![Screenshot_20210818-164143.jpg](https://user-images.githubusercontent.com/29402532/129918928-8e630877-26e7-4ff9-83de-93bbc357df8b.jpg)
Could it be that I'm using dutch instead of English?

**Comment by KieronQuinn** [comment] 2021-08-18 14:44
You do have a different UI! 

The crash is it trying to make the Snapshot button that's normally in the bottom left of the UI I have invisible, as it is broken when running as an overlay (and has no purpose anyway). Yours doesn't have the button in the first place.

Thanks, I'll just make it optional to remove - I was worried it was being caused by something else but this is a much better outcome.

**Comment by nonyonah** [comment] 2021-08-18 18:10
> ![Screenshot_20210818-164143.jpg](https://user-images.githubusercontent.com/29402532/129918928-8e630877-26e7-4ff9-83de-93bbc357df8b.jpg)
> Could it be that I'm using dutch instead of English?

Yeah I have exactly the same screen. Glad the fix is underway

**Comment by KieronQuinn** [comment] 2021-08-20 19:04
This should be fixed in 2.1, please confirm

**Comment by RikKoedoot** [comment] 2021-08-20 19:42
![Screenshot_20210820-214133.jpg](https://user-images.githubusercontent.com/29402532/130285629-c1329b0b-dc1b-448a-835d-bf67710b519b.jpg)
It is working, though as you can see the statusbar is acting weird. Should I open a new issue for this?

**Comment by KieronQuinn** [comment] 2021-08-20 19:45
Nope, that's a known issue. Can't be fixed as far as I've found.

**Closed as completed by KieronQuinn** 2021-08-20 19:45 UTC

**Comment by KieronQuinn** [comment] 2021-08-23 16:16
Spoke too soon, I put another fix in 2.2 and haven't seen it happen since. Hopefully it should be better now.

**Comment by nonyonah** [comment] 2021-08-23 16:41
Checking it now, I'll give a feedback if there's any issue

**Comment by nonyonah** [comment] 2021-08-23 16:51
No issues so far
